export const QuestionActionTypes = {
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_CURRENT_QUESTION: "SET_CURRENT_QUESTION",
  TOGGLE_QUESTION_MODAL: "TOGGLE_QUESTION_MODAL",
  TOGGLE_RATIONALE_MODAL: "TOGGLE_RATIONALE_MODAL",
  SET_IS_ANSWER_CORRECT: "SET_IS_ANSWER_CORRECT",
  RESET_QUESTION_STATE: "RESET_QUESTION_STATE",
  SET_CURRENT_ANS_PICKED: "SET_CURRENT_ANS_PICKED",
};
