export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  UPDATE_LIFE: "UPDATE_LIFE",
  SET_HAS_LOST_LIFE: "SET_HAS_LOST_LIFE",
  SET_HAS_GAIN_LIFE: "SET_HAS_GAIN_LIFE",
  RESET_USER_STATE: "RESET_USER_STATE",
  SET_LOADING: "SET_LOADING",
  SET_STREAK: "SET_STREAK",
  SET_FIVE_STREAK: "SET_FIVE_STREAK",
  TOGGLE_STAGE_MODAL: "TOGGLE_STAGE_MODAL",
  TOGGLE_WELCOME_MODAL: "TOGGLE_WELCOME_MODAL",
  TOGGLE_MUSIC_EFFECT: "TOGGLE_MUSIC_EFFECT",
  SET_MUSIC_NUM: "SET_MUSIC_NUM"
};
